// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvksyvyjcevcfdplowsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2a3N5dnlqY2V2Y2ZkcGxvd3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNTM0ODgsImV4cCI6MjA1MjcyOTQ4OH0.jyTydq_TV4a24BZpj3mm-VBgd7ww6VXK8KdJdRkupnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);